//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentstvoVer2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AgentstvoEntities3 : DbContext
    {
        private static AgentstvoEntities3 _context;
        public AgentstvoEntities3()
            : base("name=AgentstvoEntities2")
        {
        }

        public static AgentstvoEntities3 GetContext()
        {
            if (_context == null)
                _context = new AgentstvoEntities3();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appartments> Appartments { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Doljnost> Doljnost { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<TypeAppatament> TypeAppatament { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
