//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentstvoVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ID_Contract { get; set; }
        public Nullable<int> ID_House { get; set; }
        public Nullable<int> ID_Users { get; set; }
        public Nullable<int> ID_Clients { get; set; }
        public Nullable<int> ID_Options { get; set; }
        public string FIO { get; set; }
        public string Options { get; set; }
        public Nullable<System.DateTime> DateNTime { get; set; }
        public string Appartaments { get; set; }
    
        public virtual Appartments Appartments { get; set; }
        public virtual Clients Clients { get; set; }
        public virtual Options Options1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
