//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgentstvoVer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeAppatament
    {
        public int ID_TypeAppartament { get; set; }
        public string Type { get; set; }
    }
}
